server:
  port: 8081

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sns:
        region: ${AWS_SNS_REGION}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:7080/realms/christmasletterhandlingdev}
          jwk-set-uri: ${JWK_URI:http://localhost:7080/realms/christmasletterhandlingdev/protocol/openid-connect/certs}

letter-sender:
    aws:
      sns:
        topic-arn: ${AWS_SNS_TOPIC_ARN}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
