server:
  port: 8082

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sqs:
        region: ${AWS_SQS_REGION}
      dynamodb:
        endpoint: ${AWS_DYNAMODB_ENDPOINT}
        region: ${AWS_DYNAMODB_REGION}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ttl: ${REDIS_TTL}
letter-processor:
    aws:
      sqs:
        queue-url: ${AWS_SQS_QUEUE_URL}
