server:
  port: 8082

spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      sqs:
        region: ${AWS_SQS_REGION}
      dynamodb:
        endpoint: ${AWS_DYNAMODB_ENDPOINT}
        region: ${AWS_DYNAMODB_REGION}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ttl: ${REDIS_TTL}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:http://localhost:7080/realms/christmasletterhandlingdev}
          jwk-set-uri: ${JWK_URI:http://localhost:7080/realms/christmasletterhandlingdev/protocol/openid-connect/certs}

letter-processor:
    aws:
      sqs:
        queue-url: ${AWS_SQS_QUEUE_URL}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
