name: Build Pipeline for Christmas Letter Handling Project

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [letter-sender, letter-processor]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ matrix.module }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build, Test and Package
        run: mvn -pl ${{ matrix.module }}  clean install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ${{ matrix.module }}
          args: >
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=.
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

      - name: Build Docker Image
        run: mvn -pl ${{ matrix.module }} spring-boot:build-image

      - name: Login to Docker Hub
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD

      - name: Push Docker Image
        run: |
          docker tag docker.io/library/${{ matrix.module }}-service:latest $DOCKER_HUB_USERNAME/${{ matrix.module }}-service:latest
          docker push $DOCKER_HUB_USERNAME/${{ matrix.module }}-service:latest
